apiVersion: arceus/v1beta
kind: QuickStartRule
metadata:
  name: app-rule
spec:
  group: arceus
  version: v1
  templates:
    - name: nginx-temp
      template:
        name: nginx
        group: arceus
        version: v1
  settings:
    - path: /port
      targets:
        - name: nginx-temp
          sub: service
          fields:
            - path: /spec/ports/0/nodePort
    - path: /image
      targets:
        - name: nginx-temp
          sub: deploy
          fields:
            - path: /spec/template/spec/containers/0/image
    - path: /name
      targets:
        - name: nginx-temp
          fields:
            - path: /metadata/name
            - path: /metadata/labels/app
            - path: /spec/selector/matchLabels/app
            - path: /spec/template/metadata/name
            - path: /spec/template/metadata/labels/app
            - path: /spec/template/spec/containers/0/name
            - path: /spec/selector/app
