apiVersion: arceus/v1
kind: Template
metadata:
  name: nginx
spec:
  group: arceus
  version: v1
  template:
    - name: service
      apiVersion: core/v1
      kind: Service
      data: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: nginx
          labels:
            app: nginx
        spec:
          type: NodePort
          selector:
            app: nginx
          ports:
            - port: 80
              nodePort: 31180
    - name: deploy
      apiVersion: apps/v1
      kind: Deployment
      data: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx
          labels:
            app: nginx
        spec:
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              name: nginx
              labels:
                app: nginx
            spec:
              containers:
                - name: nginx
                  image: 'nginx:latest'
