apiVersion: arceus/v1beta
kind: QuickStart
metadata:
  name: nginx-rule
spec:
  templates:
    - name: nginx-temp
      group: arceus
      version: v1
      template: nginx
  settings:
    - path: /type
      targets:
        - name: nginx-temp
          sub: service
          fields:
            - path: /spec/type
    - path: /match
      targets:
        - name: nginx-temp
          sub: deploy
          fields:
            - path: /spec/template/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions